import '../app.scss'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className="bg-slate-700 py-10">{children}</body>
    </html>
  )
}
