const laptopAlert= {
  title: "Note:",
  description: "You have to bring your own laptop for this competition. We can't provide any machines for this competition.",
}
export const competitions = [
  {
    id: 1,
    name: "Competitive Programming",
    type: "CS Competition",
    status: "closed",
    min: 1,
    max: 3,
    registration_fee: 2500,
    winning: 30000,
    imageUrl: "/assets/competitive-programming.jpg",
    slug: "/competitive-programming",
  },
  {
    id: 2,
    name: "Speed Debugging",
    type: "CS Competition",
    status: "closed",
    message: "You can register for Competitive Programming.",
    min: 1,
    max: 3,
    registration_fee: 1500,
    winning: 15000,
    imageUrl: "/assets/speed-debugging.jpg",
    slug: "/speed-debugging",
  },
  {
    id: 3,
    name: "Chatcraft",
    type: "CS Competition",
    status: "closed",
    min: 1,
    max: 3,
    registration_fee: 1500,
    discount: 1000,
    winning: 15000,
    imageUrl: "/assets/chatcraft.png",
    slug: "/chatcraft",
  },
  {
    id: 4,
    name: "Database Design",
    type: "CS Competition",
    status: "closed",
    min: 1,
    max: 3,
    registration_fee: 1500,
    winning: 15000,
    imageUrl: "/assets/database-design.jpg",
    slug: "/database-design",
  },
  {
    id: 5,
    name: "Code in the Dark",
    type: "CS Competition",
    status: "closed",
    min: 1,
    max: 3,
    registration_fee: 1500,
    winning: 15000,
    imageUrl: "/assets/code-in-the-dark.jpg",
    slug: "/code-in-the-dark",
  },
  {
    id: 6,
    name: "Game Development",
    type: "CS Competition",
    status: "closed",
    min: 1,
    max: 5,
    registration_fee: 3000,
    winning: 20000,
    imageUrl: "/assets/game-development.jpg",
    slug: "/game-development",
    alert: laptopAlert
  },
  {
    id: 7,
    name: "AI Showdown",
    type: "CS Competition",
    status: "closed",
    message: "You can register for Chat Craft instead.",
    min: 1,
    max: 3,
    registration_fee: 2500,
    discount: "Free",
    winning: 30000,
    imageUrl: "/assets/ai-showdown.jpg",
    slug: "/ai-showdown",
    alert: {
      title: "Note:",
      description: "You have to bring your own laptop ( Only for Round 1).",
    }
  },
  {
    id: 8,
    name: "Hackathon",
    type: "CS Competition",
    discount: "Free",
    status: "closed",
    min: 1,
    max: 4,
    registration_fee: 2500,
    winning: 30000,
    imageUrl: "/assets/hackathon.jpg",
    slug: "/hackathon",
    alert: laptopAlert
  },
  {
    id: 9,
    name: "Code Sprint",
    type: "CS Competition",
    status: "closed",
    min: 1,
    max: 3,
    registration_fee: 2000,
    winning: 20000,
    imageUrl: "/assets/code-sprint.png",
    slug: "/code-sprint",
  },
  {
    id: 10,
    name: "Web Development",
    type: "CS Competition",
    status: "closed",
    min: 1,
    max: 3,
    registration_fee: 2000,
    winning: 30000,
    imageUrl: "/assets/web-development.jpg",
    slug: "/web-development",
    alert: laptopAlert
  },
  {
    id: 11,
    name: "Block Chain Blitz",
    type: "CS Competition",
    status: "closed",
    min: 1,
    max: 2,
    registration_fee: 1500,
    winning: 15000,
    imageUrl: "/assets/block-chain-blitz.jpg",
    slug: "/block-chain-blitz",
  },
  {
    id: 12,
    name: "UI/UX",
    type: "CS Competition",
    status: "closed",
    min: 1,
    max: 2,
    registration_fee: 1500,
    winning: 15000,
    imageUrl: "/assets/ui-ux.jpg",
    slug: "/ui-ux",
  },
  {
    id: 13,
    name: "App Development",
    status: "closed",
    type: "CS Competition",
    min: 1,
    max: 5,
    registration_fee: 3000,
    winning: 30000,
    imageUrl: "/assets/app-development.jpg",
    slug: "/app-development",
    alert: laptopAlert
  },
  {
    id: 14,
    name: "Pseudo War",
    type: "CS Competition",
    status: "closed",
    min: 1,
    max: 3,
    registration_fee: 1500,
    winning: 15000,
    imageUrl: "/assets/pseudo-war.png",
    slug: "/pseudo-war",
  },
  {
    id: 15,
    name: "Capture The Flag",
    type: "CS Competition",
    status: "closed",
    min: 1,
    max: 3,
    registration_fee: 2500,
    winning: 30000,
    imageUrl: "/assets/capture-the-flag.jpg",
    slug: "/capture-the-flag",
    alert: laptopAlert
  },
  {
    id: 16,
    name: "Auto Cad",
    type: "EE Competition",
    status: "closed",
    min: 1,
    max: 1,
    registration_fee: 1000,
    winning: 15000,
    imageUrl: "/assets/auto-cad.jpg",
    slug: "/auto-cad",
  },
  {
    id: 17,
    name: "Speed Soldering",
    type: "EE Competition",
    status: "closed",
    min: 1,
    max: 2,
    registration_fee: 2000,
    winning: 15000,
    imageUrl: "/assets/speed-soldering.jpg",
    slug: "/speed-soldering",
  },
  {
    id: 18,
    name: "Project Exhibition",
    type: "EE Competition",
    status: "closed",
    min: 1,
    max: 5,
    registration_fee: 2000,
    winning: 15000,
    imageUrl: "/assets/project-exhibition.jpg",
    slug: "/project-exhibition",
  },
  {
    id: 19,
    name: "Robo War (Light Weight)",
    type: "Robotics Competition",
    status: "closed",
    min: 2,
    max: 4,
    registration_fee: 2500,
    winning: 25000,
    imageUrl: "/assets/robo-war-light-weight.jpg",
    slug: "/robo-war-light-weight",
  },
  {
    id: 20,
    name: "Robo Sumo",
    type: "Robotics Competition",
    status: "closed",
    min: 2,
    max: 4,
    registration_fee: 1500,
    winning: 20000,
    imageUrl: "/assets/robo-sumo.jpg",
    slug: "/robo-sumo",
  },
  {
    id: 21,
    name: "Robo Soccer",
    type: "Robotics Competition",
    status: "closed",
    min: 2,
    max: 4,
    registration_fee: 1500,
    winning: 20000,
    imageUrl: "/assets/robo-soccer.jpg",
    slug: "/robo-soccer",
  },
  {
    id: 22,
    name: "Line Following Robot",
    type: "Robotics Competition",
    status: "closed",
    min: 2,
    max: 4,
    registration_fee: 1500,
    winning: 20000,
    imageUrl: "/assets/line-following-robot.jpg",
    slug: "/line-following-robot",
  },
  {
    id: 23,
    name: "FIFA",
    type: "Gaming Competition",
    status: "closed",
    min: 1,
    max: 1,
    registration_fee: 1000,
    winning: 20000,
    imageUrl: "/assets/fifa.jpg",
    slug: "/fifa",
  },
  {
    id: 24,
    name: "PUBG Mobile",
    type: "Gaming Competition",
    status: "closed",
    min: 1,
    max: 5,
    registration_fee: 1500,
    winning: 20000,
    imageUrl: "/assets/pubg-mobile.jpg",
    slug: "/pubg-mobile",
  },
  {
    id: 25,
    name: "Tekken 7",
    type: "Gaming Competition",
    status: "closed",
    min: 1,
    max: 1,
    registration_fee: 1000,
    winning: 20000,
    imageUrl: "/assets/tekken-7.jpg",
    slug: "/tekken-7",
  },
  {
    id: 26,
    name: "Chess",
    type: "General Competition",
    status: "closed",
    min: 1,
    max: 1,
    registration_fee: 1000,
    winning: 0,
    imageUrl: "/assets/chess.jpg",
    slug: "/chess",
  },
  {
    id: 27,
    name: "Photography Competition",
    type: "General Competition",
    status: "closed",
    min: 1,
    max: 1,
    registration_fee: 1000,
    winning: 0,
    imageUrl: "/assets/photography-competition.jpg",
    slug: "/photography-competition",
  },
  {
    id: 28,
    name: "Reels Competition",
    type: "General Competition",
    status: "closed",
    min: 1,
    max: 1,
    registration_fee: 1000,
    winning: 0,
    imageUrl: "/assets/reels-competition.jpg",
    slug: "/reels-competition",
  },
  {
    id: 29,
    name: "Scavenger Hunt",
    type: "General Competition",
    status: "closed",
    min: 3,
    max: 5,
    registration_fee: 1000,
    winning: 0,
    imageUrl: "/assets/scavenger-hunt.jpg",
    slug: "/scavenger-hunt",
  },
  {
    id: 30,
    name: "Dumb Charades",
    type: "General Competition",
    status: "closed",
    min: 3,
    max: 5,
    registration_fee: 1000,
    winning: 0,
    imageUrl: "/assets/dumbcharades.png",
    slug: "/dumb-charades",
  }
];

export const TeamData = [
    {
      designation: "President",
      name: "Abdullah Naeem",
      src: "/assets/abdullah.jpg",
      description: "Armed with a strong background in Marketing and an unwavering passion for technology, Abdullah is the ideal leader to propel PROCOM." 
    },
    {
      designation: "Vice President",
      name: "Umair Usman",
      src: "/assets/umair.jpg",
      description: "As the Vice President for PROCOM 2024, he's illuminating the path toward a brighter, tech-powered future."
    },
    {
      designation: "Secretary",
      name: "Munim Siddiqui",
      src: "/assets/munim.jpg",
      description: "His passion for innovation and problem-solving positions him as a standout talent with the potential to redefine the software development landscape."
    },
    {
      designation: "General Secretary",
      name: "Manahil Fatima",
      src: "/assets/manahilAnwar.jpg",
      description: "Manahil embodies exceptional leadership and a can-do attitude. She ensures that all tasks are completed efficiently and well before the deadline."
    },
    {
      designation: "Event Administrator",
      name: "Fawaz Ahmed",
      src: "/assets/fawaz.jpg",
      description: "Fawaz meticulously oversees the seamless transition of our projects from planning to execution, ensuring every detail is taken care of. "

    },
    {
      designation: "Marketing",
      name: "Maaz Imaam",
      src: "/assets/maaz.jpg",
      description: "Maaz Imam plays a vital role in communicating and joining ideas to further the advancement of the technological world."
    },
    {
      designation: "Director Branding",
      name: "Anmol Zehra",
      src: "/assets/anmolZehra.jpg",
      description: "Anmol combines technical expertise with creative brilliance, her exceptional communication skills, and people-first perspective make her the ideal branding head."
    },
    {
      designation: "Tech Head",
      name: "Ayehsa Irshad",
      src: "/assets/ayesha.jpg",
      description: "Ayesha is the driving force behind PROCOM's tech initiatives with her profound knowledge and hands-on experience in cutting-edge technologies like AI and Machine Learning."
    },
    {
      designation: "Guest Relations",
      name: "Muhammad Ahsan",
      src: "/assets/ahsan.jpg",
      description: "With a meticulous focus on detail and a passion for these complex fields, Ahsan's journey showcases his commitment to knowledge and innovation."
    },
    
    {
      designation: "Treasurer",
      name: "Usman Yaqoob",
      src: "/assets/usman.jpg",
      description: "He brings a wealth of experience to the team, having excelled in various national & international design competitions and projects."
    },
    {
      designation: "Startup Showdown",
      name: "Muhammad Hassan Tariq",
      src: "/assets/hassan.jpg",
      description: "Hasan is shaping the startup landscape. His commitment and creativity inspire those around him, fostering a spirit of innovation."
    },
    {
      designation: "Security Head",
      name: "Anas",
      src:"/assets/anas.jpg",
      description: "Anas is the guardian of PROCOM, ensuring that the event runs smoothly and securely. His dedication and commitment are second to none."
    }
  ];
